### PR TITLE
Last attempt (I hope) to fix #2720

### LINKED ISSUE #2720: in /v2/op/update if entities is empty CB crashes
in /v2/op/update if entities is empty CB crashes

#### CB version
```
  "version" : "1.5.0-next"
  "git_hash" : "d943fb6827fdee0d7e89501c343dc252f6757f60"
```

#### Request
```
curl http://qa-orion-fe-02:1026/v2/op/update -H "Content-Type: application/json" -d '{"entities": [], "actionType": "APPEND"}' 
```
#### Response
```
curl: (52) Empty reply from server
```

#### log
````
time=2016-11-25T13:07:27.918Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=rest.cpp[1123]:connectionTreat | msg=
time=2016-11-25T13:07:27.919Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=rest.cpp[1125]:connectionTreat | msg=--------------------- Serving request POST /v2/op/update -----------------
time=2016-11-25T13:07:27.919Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=rest.cpp[500]:httpHeaderGet | msg=HTTP Header:   User-Agent: curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.19.1 Basic ECC zlib/1.2.3 libidn/1.18 libssh2/1.4.2
time=2016-11-25T13:07:27.919Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=rest.cpp[500]:httpHeaderGet | msg=HTTP Header:   Host: qa-orion-fe-02:1026
time=2016-11-25T13:07:27.919Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=rest.cpp[500]:httpHeaderGet | msg=HTTP Header:   Accept: */*
time=2016-11-25T13:07:27.919Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=rest.cpp[500]:httpHeaderGet | msg=HTTP Header:   Content-Type: application/json
time=2016-11-25T13:07:27.919Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=rest.cpp[500]:httpHeaderGet | msg=HTTP Header:   Content-Length: 40
time=2016-11-25T13:07:27.919Z | lvl=DEBUG | corr=1d9f04d4-b310-11e6-86a3-005056a20feb | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=sem.cpp[276]:transSemTake | msg=transactionIdSet taking the 'trans' semaphore for 'changing the transaction id'
time=2016-11-25T13:07:27.919Z | lvl=DEBUG | corr=1d9f04d4-b310-11e6-86a3-005056a20feb | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=sem.cpp[297]:transSemTake | msg=transactionIdSet has the 'trans' semaphore
time=2016-11-25T13:07:27.919Z | lvl=DEBUG | corr=1d9f04d4-b310-11e6-86a3-005056a20feb | trans=1480079224-063-00000000002 | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=sem.cpp[373]:transSemGive | msg=transactionIdSet gives the 'trans' semaphore for 'changing the transaction id'
time=2016-11-25T13:07:27.919Z | lvl=INFO | corr=1d9f04d4-b310-11e6-86a3-005056a20feb | trans=1480079224-063-00000000002 | from=pending | srv=pending | subsrv=pending | comp=Orion | op=logMsg.h[1808]:lmTransactionStart | msg=Starting transaction from 127.0.1.1:53972/v2/op/update
time=2016-11-25T13:07:27.919Z | lvl=DEBUG | corr=1d9f04d4-b310-11e6-86a3-005056a20feb | trans=1480079224-063-00000000002 | from=127.0.1.1 | srv=pending | subsrv=pending | comp=Orion | op=rest.cpp[1231]:connectionTreat | msg=Got 40 of payload of 40 bytes
time=2016-11-25T13:07:27.919Z | lvl=DEBUG | corr=1d9f04d4-b310-11e6-86a3-005056a20feb | trans=1480079224-063-00000000002 | from=127.0.1.1 | srv=pending | subsrv=<default> | comp=Orion | op=ContextAttribute.cpp[157]:ContextAttribute | msg=Creating a ContextAttribute 1
time=2016-11-25T13:07:27.919Z | lvl=DEBUG | corr=1d9f04d4-b310-11e6-86a3-005056a20feb | trans=1480079224-063-00000000002 | from=127.0.1.1 | srv=pending | subsrv=<default> | comp=Orion | op=ContextAttribute.cpp[157]:ContextAttribute | msg=Creating a ContextAttribute 1
time=2016-11-25T13:07:27.919Z | lvl=DEBUG | corr=1d9f04d4-b310-11e6-86a3-005056a20feb | trans=1480079224-063-00000000002 | from=127.0.1.1 | srv=pending | subsrv=<default> | comp=Orion | op=ContextAttribute.cpp[157]:ContextAttribute | msg=Creating a ContextAttribute 1
time=2016-11-25T13:07:27.919Z | lvl=DEBUG | corr=1d9f04d4-b310-11e6-86a3-005056a20feb | trans=1480079224-063-00000000002 | from=127.0.1.1 | srv=pending | subsrv=<default> | comp=Orion | op=RestService.cpp[533]:restService | msg=Parsing payload for URL '/v2/op/update', method 'POST', service vector index: 33
time=2016-11-25T13:07:27.919Z | lvl=DEBUG | corr=1d9f04d4-b310-11e6-86a3-005056a20feb | trans=1480079224-063-00000000002 | from=127.0.1.1 | srv=pending | subsrv=<default> | comp=Orion | op=RestService.cpp[535]:restService | msg=Parsing payload '{"entities": [], "actionType": "APPEND"}'
time=2016-11-25T13:07:27.920Z | lvl=DEBUG | corr=1d9f04d4-b310-11e6-86a3-005056a20feb | trans=1480079224-063-00000000002 | from=127.0.1.1 | srv=pending | subsrv=<default> | comp=Orion | op=RestService.cpp[108]:payloadParse | msg=parsing data for service 'BatchUpdateRequest'. Method: 'POST'
time=2016-11-25T13:07:27.920Z | lvl=DEBUG | corr=1d9f04d4-b310-11e6-86a3-005056a20feb | trans=1480079224-063-00000000002 | from=127.0.1.1 | srv=pending | subsrv=<default> | comp=Orion | op=RestService.cpp[109]:payloadParse | msg=outMimeType: JSON
time=2016-11-25T13:07:27.920Z | lvl=DEBUG | corr=1d9f04d4-b310-11e6-86a3-005056a20feb | trans=1480079224-063-00000000002 | from=127.0.1.1 | srv=pending | subsrv=<default> | comp=Orion | op=RestService.cpp[134]:payloadParse | msg=result:      'OK'
time=2016-11-25T13:07:27.920Z | lvl=DEBUG | corr=1d9f04d4-b310-11e6-86a3-005056a20feb | trans=1480079224-063-00000000002 | from=127.0.1.1 | srv=pending | subsrv=<default> | comp=Orion | op=RestService.cpp[135]:payloadParse | msg=outMimeType: 'JSON'
time=2016-11-25T13:07:27.920Z | lvl=DEBUG | corr=1d9f04d4-b310-11e6-86a3-005056a20feb | trans=1480079224-063-00000000002 | from=127.0.1.1 | srv=pending | subsrv=<default> | comp=Orion | op=RestService.cpp[537]:restService | msg=payloadParse returns 'OK'
time=2016-11-25T13:07:27.920Z | lvl=DEBUG | corr=1d9f04d4-b310-11e6-86a3-005056a20feb | trans=1480079224-063-00000000002 | from=127.0.1.1 | srv=pending | subsrv=<default> | comp=Orion | op=RestService.cpp[559]:restService | msg=Treating service POST /v2/op/update
time=2016-11-25T13:07:27.920Z | lvl=DEBUG | corr=1d9f04d4-b310-11e6-86a3-005056a20feb | trans=1480079224-063-00000000002 | from=127.0.1.1 | srv=<default> | subsrv=<default> | comp=Orion | op=RestService.cpp[600]:restService | msg=tenant: ''
time=2016-11-25T13:07:27.920Z | lvl=DEBUG | corr=1d9f04d4-b310-11e6-86a3-005056a20feb | trans=1480079224-063-00000000002 | from=127.0.1.1 | srv=<default> | subsrv=<default> | comp=Orion | op=ContextElementVector.cpp[88]:present | msg=0 ContextElements
time=2016-11-25T13:07:27.920Z | lvl=DEBUG | corr=1d9f04d4-b310-11e6-86a3-005056a20feb | trans=1480079224-063-00000000002 | from=127.0.1.1 | srv=<default> | subsrv=<default> | comp=Orion | op=UpdateActionType.cpp[105]:present | msg=UpdateActionType: APPEND
time=2016-11-25T13:07:27.920Z | lvl=DEBUG | corr=1d9f04d4-b310-11e6-86a3-005056a20feb | trans=1480079224-063-00000000002 | from=127.0.1.1 | srv=<default> | subsrv=<default> | comp=Orion | op=sem.cpp[147]:reqSemTake | msg=mongoUpdateContext taking the 'req' semaphore for 'ngsi10 update request'
time=2016-11-25T13:07:27.920Z | lvl=DEBUG | corr=1d9f04d4-b310-11e6-86a3-005056a20feb | trans=1480079224-063-00000000002 | from=127.0.1.1 | srv=<default> | subsrv=<default> | comp=Orion | op=sem.cpp[168]:reqSemTake | msg=mongoUpdateContext has the 'req' semaphore
time=2016-11-25T13:07:27.920Z | lvl=DEBUG | corr=1d9f04d4-b310-11e6-86a3-005056a20feb | trans=1480079224-063-00000000002 | from=127.0.1.1 | srv=<default> | subsrv=<default> | comp=Orion | op=sem.cpp[353]:reqSemGive | msg=mongoUpdateContext gives the 'req' semaphore for 'ngsi10 update request'
```

### PR DESCRIPTION
**Pull request by fgalan**
Fixes #2720 

Unit test 100%

Test harness 100% (except 2 ones that I hthink are due to local setup)

### CODE REVIEW

File: src/lib/serviceRoutinesV2/postBatchUpdate.cpp [hunk 1]
```diff
@@ -68,22 +68,22 @@ std::string postBatchUpdate
...
+
   std::string  answer = "";
   if (parseDataP->upcr.res.contextElementVector.size() == 0)
   {
     OrionError oe(SccBadRequest, ERROR_DESC_BAD_REQUEST_EMPTY_ENTITIES_VECTOR);
     alarmMgr.badInput(clientIp, ERROR_DESC_BAD_REQUEST_EMPTY_ENTITIES_VECTOR);
 
-    TIMED_RENDER(answer = oe.toJson());
-
+    TIMED_RENDER(answer = oe.smartRender(V2););
```
Comment (kzangeli) [inline src/lib/serviceRoutinesV2/postBatchUpdate.cpp]: Extra ';'

Comment (fgalan) [inline src/lib/serviceRoutinesV2/postBatchUpdate.cpp]: Fixed in d74d317.

**Comment by kzangeli** [comment]
LGTM
