### PR TITLE
FIX urls that make Orion to crash

### LINKED ISSUE #2092: in POST v2/subscriptions with some "notification-http-url" values, CB is stopped
in POST v2/subscriptions with some "notification-http-url" values, CB is stopped, but does not show any extra info in console or log

#### dataset
      | url                        |
      |----------------------------|
      | //                         |
      | ///                        |
      | http:///a                  |

#### subscription request
```
POST http://localhost:1026/v2/subscriptions
Content-Type: application/json
Fiware-Service: test_notification_http_url_error
Fiware-ServicePath: /test
{"notification": {"http": {"url": "//"}, "attrs": ["temperature"]}, "expires": "2016-04-05T14:00:00.00Z", "subject": {"entities": [{"idPattern": ".*"}], "condition": {"attrs": ["temperature"]}}}
```

#### log
```
time=2016-04-27T10:04:08.632CEST | lvl=DEBUG | corr=N/A | trans=N/A | srv=N/A | subsrv=N/A | from=N/A | function=connectionTreat | comp=Orion | msg=rest.cpp[955]:
time=2016-04-27T10:04:08.632CEST | lvl=DEBUG | corr=N/A | trans=N/A | srv=N/A | subsrv=N/A | from=N/A | function=connectionTreat | comp=Orion | msg=rest.cpp[956]: --------------------- Serving request POST /v2/subscriptions/ -----------------
time=2016-04-27T10:04:08.632CEST | lvl=DEBUG | corr=N/A | trans=N/A | srv=N/A | subsrv=N/A | from=N/A | function=httpHeaderGet | comp=Orion | msg=rest.cpp[274]: HTTP Header:   HOST: qa-orion-fe-02:1026
time=2016-04-27T10:04:08.632CEST | lvl=DEBUG | corr=N/A | trans=N/A | srv=N/A | subsrv=N/A | from=N/A | function=httpHeaderGet | comp=Orion | msg=rest.cpp[274]: HTTP Header:   fiware-service: test_update_happy_path
time=2016-04-27T10:04:08.632CEST | lvl=DEBUG | corr=N/A | trans=N/A | srv=N/A | subsrv=N/A | from=N/A | function=httpHeaderGet | comp=Orion | msg=rest.cpp[274]: HTTP Header:   fiware-servicepath: /test
time=2016-04-27T10:04:08.632CEST | lvl=DEBUG | corr=N/A | trans=N/A | srv=N/A | subsrv=N/A | from=N/A | function=httpHeaderGet | comp=Orion | msg=rest.cpp[274]: HTTP Header:   content-type: application/json
time=2016-04-27T10:04:08.632CEST | lvl=DEBUG | corr=N/A | trans=N/A | srv=N/A | subsrv=N/A | from=N/A | function=httpHeaderGet | comp=Orion | msg=rest.cpp[274]: HTTP Header:   content-length: 198
time=2016-04-27T10:04:08.633CEST | lvl=DEBUG | corr=9e6d4fe4-0c4e-11e6-b405-005056a20feb | trans=N/A | srv=N/A | subsrv=N/A | from=N/A | function=transSemTake | comp=Orion | msg=sem.cpp[276]: transactionIdSet taking the 'trans' semaphore for 'changing the transaction id'
time=2016-04-27T10:04:08.633CEST | lvl=DEBUG | corr=9e6d4fe4-0c4e-11e6-b405-005056a20feb | trans=N/A | srv=N/A | subsrv=N/A | from=N/A | function=transSemTake | comp=Orion | msg=sem.cpp[297]: transactionIdSet has the 'trans' semaphore
time=2016-04-27T10:04:08.633CEST | lvl=DEBUG | corr=9e6d4fe4-0c4e-11e6-b405-005056a20feb | trans=1461744234-431-00000000001 | srv=N/A | subsrv=N/A | from=N/A | function=transSemGive | comp=Orion | msg=sem.cpp[373]: transactionIdSet gives the 'trans' semaphore for 'changing the transaction id'
time=2016-04-27T10:04:08.633CEST | lvl=INFO | corr=9e6d4fe4-0c4e-11e6-b405-005056a20feb | trans=1461744234-431-00000000001 | srv=pending | subsrv=pending | from=pending | function=lmTransactionStart | comp=Orion | msg=logMsg.h[1805]: Starting transaction from 10.95.232.173:62772/v2/subscriptions/
time=2016-04-27T10:04:08.633CEST | lvl=DEBUG | corr=9e6d4fe4-0c4e-11e6-b405-005056a20feb | trans=1461744234-431-00000000001 | srv=pending | subsrv=pending | from=10.95.232.173 | function=connectionTreat | comp=Orion | msg=rest.cpp[1059]: Got 198 of payload of 198 bytes
time=2016-04-27T10:04:08.633CEST | lvl=DEBUG | corr=9e6d4fe4-0c4e-11e6-b405-005056a20feb | trans=1461744234-431-00000000001 | srv=pending | subsrv=/test | from=10.95.232.173 | function=servicePathSplit | comp=Orion | msg=rest.cpp[698]: Service Path 0: '/test'
time=2016-04-27T10:04:08.633CEST | lvl=DEBUG | corr=9e6d4fe4-0c4e-11e6-b405-005056a20feb | trans=1461744234-431-00000000001 | srv=pending | subsrv=/test | from=10.95.232.173 | function=ContextAttribute | comp=Orion | msg=ContextAttribute.cpp[259]: Creating a ContextAttribute 1
time=2016-04-27T10:04:08.633CEST | lvl=DEBUG | corr=9e6d4fe4-0c4e-11e6-b405-005056a20feb | trans=1461744234-431-00000000001 | srv=pending | subsrv=/test | from=10.95.232.173 | function=ContextAttribute | comp=Orion | msg=ContextAttribute.cpp[259]: Creating a ContextAttribute 1
time=2016-04-27T10:04:08.633CEST | lvl=DEBUG | corr=9e6d4fe4-0c4e-11e6-b405-005056a20feb | trans=1461744234-431-00000000001 | srv=pending | subsrv=/test | from=10.95.232.173 | function=ContextAttribute | comp=Orion | msg=ContextAttribute.cpp[259]: Creating a ContextAttribute 1
time=2016-04-27T10:04:08.634CEST | lvl=DEBUG | corr=9e6d4fe4-0c4e-11e6-b405-005056a20feb | trans=1461744234-431-00000000001 | srv=pending | subsrv=/test | from=10.95.232.173 | function=restService | comp=Orion | msg=RestService.cpp[411]: Parsing payload for URL '/v2/subscriptions', method 'POST', service vector index: 25
time=2016-04-27T10:04:08.634CEST | lvl=DEBUG | corr=9e6d4fe4-0c4e-11e6-b405-005056a20feb | trans=1461744234-431-00000000001 | srv=pending | subsrv=/test | from=10.95.232.173 | function=restService | comp=Orion | msg=RestService.cpp[413]: Parsing payload '{"notification": {"http": {"url": "//"}, "attrs": ["temperature"]}, "expires": "2016-04-05T14:00:00.00Z", "subject": {"entities": [{"idPattern": ".*"}], "condition": {"attrs": ["temperature"]}}}

'
time=2016-04-27T10:04:08.634CEST | lvl=DEBUG | corr=9e6d4fe4-0c4e-11e6-b405-005056a20feb | trans=1461744234-431-00000000001 | srv=pending | subsrv=/test | from=10.95.232.173 | function=payloadParse | comp=Orion | msg=RestService.cpp[101]: parsing data for service 'SubscriptionsRequest'. Method: 'POST'
time=2016-04-27T10:04:08.634CEST | lvl=DEBUG | corr=9e6d4fe4-0c4e-11e6-b405-005056a20feb | trans=1461744234-431-00000000001 | srv=pending | subsrv=/test | from=10.95.232.173 | function=payloadParse | comp=Orion | msg=RestService.cpp[102]: outFormat: JSON
```

### PR DESCRIPTION
**Pull request by fgalan**
Fixes #2092 

@kzangeli 
@crbrox

### CODE REVIEW

File: CHANGES_NEXT_RELEASE [hunk 1]
```diff
@@ -23,3 +23,4 @@
 - Add: change/add path /entities/{id}/attrs (#2028)
 - Deprecate: "location" metadata to specify entity location
 - Fix: JSON response in log management operations
+- Fix: invalid URLs at subscription time that make Orion to crash (#2092)
```
Comment (kzangeli) [inline CHANGES_NEXT_RELEASE]: The test is not very descriptive ...

Fix: capturing invalid URLs at subscription time (and returning error response) that otherwise would make Orion crash

Comment (fgalan) [inline CHANGES_NEXT_RELEASE]: Fixed in 9f5bd23faaeded4381cc08a102a581ee2f1ca886

File: src/lib/common/string.cpp [hunk 2]
```diff
@@ -254,14 +254,20 @@ bool parseUrl(const std::string& url, std::string& host, int& port, std::string&
...
-  if ((protocol != "https:") && (protocol != "http:"))
+  if ((urlTokens.size() == 0) || ((urlTokens[0] != "https:") && (urlTokens[0] != "http:")))
+  {
+    return false;
+  }
+
+  //
+  // Ensuring the host is present
+  //
+  if (urlTokens[2] == "")
```
Comment (kzangeli) [inline src/lib/common/string.cpp]: This might cause a crash as well ... Right?
Better something like this:

    if ((urlTokens.size() < 3) || (urlTokens[2] == ""))

File: test/functionalTest/cases/2092_incorrect_url_bug/check_incorrect_urls.test [hunk 3]
```diff
@@ -0,0 +1,161 @@
...
+Context subscripion description field
+
+--SHELL-INIT--
+dbInit CB
+brokerStart CB 0-255
+
+--SHELL--
+
+#
+# 01. Create subscription without url // and get error
```
Comment (kzangeli) [inline test/functionalTest/cases/2092_incorrect_url_bug/check_incorrect_urls.test]: without => with ?

File: test/functionalTest/cases/2092_incorrect_url_bug/check_incorrect_urls.test [hunk 4]
```diff
@@ -0,0 +1,161 @@
...
+01. Create subscription without url // and get error
+====================================================
+HTTP/1.1 400 Bad Request
+Content-Length: 50
+Content-Type: application/json
+Fiware-Correlator: REGEX([0-9a-f\-]{36})
+Date: REGEX(.*)
+
+{
+    "description": "Invalid URL",
```
Comment (kzangeli) [inline test/functionalTest/cases/2092_incorrect_url_bug/check_incorrect_urls.test]: I find this description a little dry ...

Invalid URL for notifications ?

Otherwise you could understand that the broker is complaining about the URL of the subscription request (which would probably be a 404 not found, but still)

File: src/lib/common/string.cpp (hunk 2 above)
Comment (fgalan) [inline src/lib/common/string.cpp]: Fixed in c2085e268d89634164d5dfe9a093f32df0c8d74e

File: test/functionalTest/cases/2092_incorrect_url_bug/check_incorrect_urls.test (hunk 4 above)
Comment (fgalan) [inline test/functionalTest/cases/2092_incorrect_url_bug/check_incorrect_urls.test]: I know but... it this really part of #2092?

Comment (kzangeli) [inline test/functionalTest/cases/2092_incorrect_url_bug/check_incorrect_urls.test]: Probably not, new issue?

Comment (fgalan) [inline test/functionalTest/cases/2092_incorrect_url_bug/check_incorrect_urls.test]: I'll have a look and try to fix in this very PR.

File: test/functionalTest/cases/2092_incorrect_url_bug/check_incorrect_urls.test (hunk 3 above)
Comment (fgalan) [inline test/functionalTest/cases/2092_incorrect_url_bug/check_incorrect_urls.test]: Fixed in https://github.com/telefonicaid/fiware-orion/pull/2094/commits/d5fdb11af922ead127a932a178a1134c0a4d8d56

File: test/functionalTest/cases/2092_incorrect_url_bug/check_incorrect_urls.test (hunk 4 above)
Comment (fgalan) [inline test/functionalTest/cases/2092_incorrect_url_bug/check_incorrect_urls.test]: At the end fixed in this PR (only for NGSIv2... for other usages of parseUrl() is difficult). The following URL is used:

"Invalid URL parsing notification url"

A bit redundant ("URL" and "url") but I think is not a big problem.

Fixed in https://github.com/telefonicaid/fiware-orion/pull/2094/commits/6f9b907292d8a892b5e2cbbc0724850c3f0fc7b4

**Comment by kzangeli** [comment]
LGTM

**Comment by crbrox** [comment]
LGTM
