### PR TITLE
FIX proper 500 Internal Server Error response with descriptive text when "sort fail" at DB occur

### LINKED ISSUE #2752: Proper 500 response when "sort fail" at DB occur
Raised at http://stackoverflow.com/questions/40376277/fiware-orion-context-broker-offset-parameter-behaviour/40999725#40999725

Orion should return a proper 500 error with a descriptive text pointing to documentation when this situation occurs (currently a 200 OK and a weir payload is returned).

### PR DESCRIPTION
**Pull request by fgalan**
Fixes #2752 

Manually tested (unfortunatelly this requires a particular DB to raise the problem, not easy to automate in functional tests):

```
fermin@neodeb:~/src/fiware-orion/test/functionalTest$ curl -vvvv -s -S 'localhost:1026/v1/contextEntities?offset=54882' 
* Hostname was NOT found in DNS cache
*   Trying ::1...
* Connected to localhost (::1) port 1026 (#0)
> GET /v1/contextEntities?offset=54882 HTTP/1.1
> User-Agent: curl/7.38.0
> Host: localhost:1026
> Accept: */*
> 
< HTTP/1.1 200 OK
< Connection: Keep-Alive
< Content-Length: 416
< Content-Type: application/json
< Fiware-Correlator: 05eeb236-bc51-11e6-bab4-000c29173617
< Date: Wed, 07 Dec 2016 07:44:46 GMT
< 
{
  "contextResponses" : [
    {
      "contextElement" : {
        "type" : "",
        "isPattern" : "true",
        "id" : ".*"
      },
      "statusCode" : {
        "code" : "500",
        "reasonPhrase" : "Internal Server Error",
        "details" : "Sort operation used more than the maximum RAM. You should create an index. Check Database Administration section at Orion documentation."
      }
    }
  ]
}
* Connection #0 to host localhost left intact
fermin@neodeb:~/src/fiware-orion/test/functionalTest$ curl -vvvv -s -S 'localhost:1026/v2/entities?offset=54882' | python -mjson.tool
* Hostname was NOT found in DNS cache
*   Trying ::1...
* Connected to localhost (::1) port 1026 (#0)
> GET /v2/entities?offset=54882 HTTP/1.1
> User-Agent: curl/7.38.0
> Host: localhost:1026
> Accept: */*
> 
< HTTP/1.1 500 Internal Server Error
< Connection: Keep-Alive
< Content-Length: 184
< Content-Type: application/json
< Fiware-Correlator: 07dad78c-bc51-11e6-8930-000c29173617
< Date: Wed, 07 Dec 2016 07:44:49 GMT
< 
{ [data not shown]
* Connection #0 to host localhost left intact
{
    "description": "Sort operation used more than the maximum RAM. You should create an index. Check Database Administration section at Orion documentation.",
    "error": "InternalServerError"
}
```

### CODE REVIEW

File: src/lib/apiTypesV2/Entities.cpp [hunk 1]
```diff
@@ -145,15 +145,29 @@ void Entities::fill(QueryContextResponse* qcrsP)
...
-
-    eP->attributeVector.fill(&ceP->contextAttributeVector);
-    vec.push_back(eP);
+    StatusCode* scP = &qcrsP->contextElementResponseVector[ix]->statusCode;
+
+    if (scP->code == SccReceiverInternalError)
+    {
+      // Do we need to release the memory allocated in 'vec' before returning? I don't
+      // think so, as the releasing logic in the upper layer will deal with that but
+      // let's do anyway just in case...
```
Comment (kzangeli) [inline src/lib/apiTypesV2/Entities.cpp]: No, this should not be necessary.
i would remove the call to `vec.release` and the comment and let valgrind tell us (it *is* a special casa as it gives back an error).
Unnecessary code and comments only confuse ...

File: src/lib/mongoBackend/MongoGlobal.cpp [hunk 2]
```diff
@@ -1282,6 +1283,10 @@ bool entitiesQuery
       {
         exErr = invalidPolygon;
       }
+      else if (strncmp(exErr.c_str(), sortError, strlen(sortError)) == 0)
+      {
+        exErr = "Sort operation used more than the maximum RAM. You should create an index. Check Database Administration section at Orion documentation.";
```
Comment (fgalan) [inline src/lib/mongoBackend/MongoGlobal.cpp]: We cannot use `'`. It is a forbiddenc char... :(

Comment (kzangeli) [inline src/lib/mongoBackend/MongoGlobal.cpp]: ok, so:

Check Database Administration section at Orion documentation.  =>
Check the Database Administration section in Orion documentation

Not perfect, but good enough ...

Comment (fgalan) [inline src/lib/mongoBackend/MongoGlobal.cpp]: Fixed in b81c5b5f6972d57a6c67a2fe2828779b8344199f (doc) and 49b7e5f4d9f094144566e86fa89adc03b3c74e6b (code)
