### PR TITLE
Bug/2893 case insensitive custom notif http headers

### LINKED ISSUE #2893: case sensitivness in httpCustom notification
A small bug, but that can bite (it did ;).
I tried to create a notification with Orion, using httpCustom and a `Content-Type: application/json`.
I used the encoding suggested at: http://fiware-orion.readthedocs.io/en/master/user/forbidden_characters/#custom-payload-special-treatment

```
curl localhost:1026/v2/subscriptions -s -S --header 'Content-Type: application/json' --header 'Accept: application/json' -d @- <<EOF
{
  "description": "",
  "subject": {
    "entities": [
      {
        "id": "WS_UPPA_Sensor2",
        "type": "SensingDevice"
      }
    ],
    "condition": {
      "attrs": [
        "SM1"
      ]
    }
  },
  "notification": {
    "httpCustom": {
      "url": "http://localhost:10839",
      "headers": {
         "Content-Type": "application/json"
      },
      "method": "POST",      
      "payload": "%7B%22src%22%3A%2200393806412092%22%2C%22dst%22%3A%2200393806412093%22%2C%22text%22%3A%22test%22%7D"
    },
    "attrs": [
      "SM1"
    ]
  },
  "expires": "2040-01-01T14:00:00.00Z",
  "throttling": 5
}
EOF
```

Listening on the notification port I get:
```
$ ncat -v -l 10839 
POST / HTTP/1.1
Host: localhost:10839
User-Agent: orion/1.7.0-next libcurl/7.47.0
Fiware-ServicePath: /UPPA/TESTS
Accept: application/json
Content-length: 61
Content-type: text/plain; charset=utf-8
Fiware-Correlator: e3c0e990-3c93-11e7-94a9-605718b19667
Ngsiv2-AttrsFormat: custom
Content-Type: application/json
```

You see that `Content-Type` is repeated twice, with different cases. This didn't work well with my provider.
If I put `Content-type` in the httpCustom headers, it works.
As per: https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2
field names should be case-insensitive.
Thanks!

### PR DESCRIPTION
**Pull request by arigliano**
This PR fixes #2893 issue.

Now default notification headers are correctly replaced with the ones present in the custom headers map, in a case insensitive way.

In detail,

-  Headers name in the custom map are lowercased before insertion, in order to correctly match with the default ones, in the **httpHeaderAdd** function.
- This last function was modified in its signature and a bit in its logic. Now it accepts **headerName** and **headerValue**, in order to compose the final header, eventually replacing with a custom one from the relative map.
- Consequently, the **httpRequestSendWithCurl** body was modified, in those parts where default headers are passed to the **httpHeaderAdd**.

### CODE REVIEW

File: src/lib/ngsiNotify/Notifier.cpp [hunk 1]
```diff
@@ -1,569 +1,570 @@
...
+    params->content          = payloadString;
+    params->mimeType         = JSON;
+    params->renderFormat     = renderFormatToString(renderFormat);
+    params->fiwareCorrelator = fiwareCorrelator;
+    params->subscriptionId   = ncrP->subscriptionId.get();
+    params->registration     = false;
+
+    paramsV->push_back(params);
+    return paramsV;
+}
```
Comment (kzangeli) [inline src/lib/ngsiNotify/Notifier.cpp]: Why do we see the entire file as modified?
Can only suspect windows line feed/carriage return ...
It's not possible to view the real change like this, please try and redo the chamges to this file so that the diff shows only the affected lines.

File: src/lib/rest/httpRequestSend.cpp [hunk 2]
```diff
@@ -387,17 +380,19 @@ int httpRequestSendWithCurl
...
     snprintf(rushHeaderPortAsString, sizeof(rushHeaderPortAsString), "%d", rushHeaderPort);
-    headerRushHttp = "X-relayer-host: " + rushHeaderIP + ":" + rushHeaderPortAsString;
-    LM_T(LmtHttpHeaders, ("HTTP-HEADERS: '%s'", headerRushHttp.c_str()));
+    rushHeaderValue = rushHeaderIP + ":" + rushHeaderPortAsString;
+    LM_T(LmtHttpHeaders, ("HTTP-HEADERS: '%s'", (rushHostHeaderName + ": " + rushHeaderValue).c_str()));
     httpHeaderAdd(&headers,
-                  "X-relayer-host",
-                  headerRushHttp,
+    		      rushHostHeaderName,
+				  rushHeaderValue,
```
Comment (kzangeli) [inline src/lib/rest/httpRequestSend.cpp]: Indents

File: src/lib/rest/httpRequestSend.cpp [hunk 3]
```diff
@@ -387,17 +380,19 @@ int httpRequestSendWithCurl
     char         rushHeaderPortAsString[STRING_SIZE_FOR_INT];
     uint16_t     rushHeaderPort     = port;
     std::string  rushHeaderIP       = ip;
-    std::string  headerRushHttp;
+    std::string  rushHeaderValue;
+    std::string  rushHostHeaderName = "X-relayer-host";
+    std::string  rushProtocolHeaderName = "X-relayer-protocol";
```
Comment (kzangeli) [inline src/lib/rest/httpRequestSend.cpp]: Indents

File: src/lib/rest/httpRequestSend.cpp [hunk 4]
```diff
@@ -406,45 +401,50 @@ int httpRequestSendWithCurl
...
     }
   }
 
   snprintf(portAsString, sizeof(portAsString), "%u", port);
 
   // ----- User Agent
   char cvBuf[CURL_VERSION_MAX_LENGTH];
-  char headerUserAgent[HTTP_HEADER_USER_AGENT_MAX_LENGTH];
+  char userAgentHeaderValue[HTTP_HEADER_USER_AGENT_MAX_LENGTH];
+  std::string userAgentHeaderName = "User-Agent";
```
Comment (kzangeli) [inline src/lib/rest/httpRequestSend.cpp]: Indents

File: src/lib/rest/httpRequestSend.cpp [hunk 5]
```diff
@@ -406,45 +401,50 @@ int httpRequestSendWithCurl
...
+  httpHeaderAdd(&headers, fiwareServicePathHeaderName, fiwareServicePathHeaderValue, &outgoingMsgSize, extraHeaders, usedExtraHeaders);
 
   // ----- X-Auth-Token
   if (xauthToken != "")
   {
-    std::string xauthTokenString = std::string("X-Auth-Token: ") + xauthToken;
-    httpHeaderAdd(&headers, "X-Auth-Token", xauthTokenString, &outgoingMsgSize, extraHeaders, usedExtraHeaders);
+    std::string xauthTokenHeaderName = "X-Auth-Token";
+    std::string xauthTokenHeaderValue = xauthToken;
+    httpHeaderAdd(&headers, xauthTokenHeaderName, xauthTokenHeaderValue, &outgoingMsgSize, extraHeaders, usedExtraHeaders);
```
Comment (kzangeli) [inline src/lib/rest/httpRequestSend.cpp]: We try to indent the variables and the equal sign.
The code is a little easier to read that way.
There are plenty of unindented vars in the PR.
Easy enough to fix.

And, remember, TABs are strictly forbidden!

File: test/functionalTest/cases/2893_case_insensitive_custom_notif_http_headers/case_insensitive_custom_notif_http_headers.test [hunk 6]
```diff
@@ -0,0 +1,153 @@
...
+03. Dump accumulator, see 1 notification
+========================================
+POST http://127.0.0.1:REGEX(\d+)/notify
+Fiware-Servicepath: /
+Content-Length: 299
+User-Agent: orion/REGEX(\d+\.\d+\.\d+.*)
+Ngsiv2-Attrsformat: normalized
+Host: 127.0.0.1:REGEX(\d+)
+Accept: application/json
+Content-Type: application/json
```
Comment (kzangeli) [inline test/functionalTest/cases/2893_case_insensitive_custom_notif_http_headers/case_insensitive_custom_notif_http_headers.test]: Which header prevails?
The "normal one" or the one "from httpCustom"?

This is not for this PR, but interesting nevertheless.

I mean, if yoy had picked A4 == " plain/text", would we get TWO Content-Type headers? Or only one?
If only one, which one?

Comment (fgalan) [reply test/functionalTest/cases/2893_case_insensitive_custom_notif_http_headers/case_insensitive_custom_notif_http_headers.test]: Except in the case of non-modificable headers (`Fiware-Correlator` and `NgsiV2-AttrsFormat` see #2937), the one produced as a consecuence of httpCustom must prevail.

File: src/lib/rest/httpRequestSend.cpp (hunk 5 above)
Comment (fgalan) [reply src/lib/rest/httpRequestSend.cpp]: > And, remember, TABs are strictly forbidden!

Yeah, rule M4 https://github.com/telefonicaid/fiware-orion/blob/master/doc/manuals/contribution_guidelines.md#m4-indent ;)

File: src/lib/ngsiNotify/Notifier.cpp (hunk 1 above)
Comment (arigliano) [reply src/lib/ngsiNotify/Notifier.cpp]: Fixed in 273e069

File: src/lib/rest/httpRequestSend.cpp [hunk 7]
```diff
@@ -143,7 +143,7 @@ static char* curlVersionGet(char* buf, int bufLen)
 * PARAMETERS
```
Comment (fgalan) [inline src/lib/rest/httpRequestSend.cpp]: An entry in the CHANGES_NEXT_RELEASE file should be added with regards to this PR. Suggestion:

```
-Fix: case-senstive header duplication (e.g. "Content-Type" and "Content-type") in custom notifications (#2893)
```

File: src/lib/rest/httpRequestSend.cpp [hunk 8]
```diff
@@ -258,7 +251,7 @@ int httpRequestSendWithCurl
    const std::string&                         orig_content_type,
    const std::string&                         content,
    const std::string&                         fiwareCorrelation,
-   const std::string&                         ngisv2AttrFormat,
```
Comment (fgalan) [inline src/lib/rest/httpRequestSend.cpp]: Is this an actual change? Mabye another TAB should be replace by space indents here...

File: src/lib/rest/httpRequestSend.cpp [hunk 9]
```diff
@@ -708,7 +715,7 @@ int httpRequestSend
                                      orig_content_type,
                                      content,
                                      fiwareCorrelation,
-                                     ngisv2AttrFormat,
```
Comment (fgalan) [inline src/lib/rest/httpRequestSend.cpp]: Is this an actual change? Maybe another TAB should be replace by space indents here...

File: test/functionalTest/cases/2893_case_insensitive_custom_notif_http_headers/case_insensitive_custom_notif_http_headers.test [hunk 10]
```diff
@@ -0,0 +1,153 @@
...
+
+
+echo "02. Create E1 with attributes A1, A2, A3 and A4"
+echo "==============================================="
+payload='{
+  "id": "E1",
+  "A1": "foo",
+  "A2": "bar",
+  "A3": "Content-Type" ,
+  "A4": "application/json"
```
Comment (fgalan) [inline test/functionalTest/cases/2893_case_insensitive_custom_notif_http_headers/case_insensitive_custom_notif_http_headers.test]: I'd suggest to use something that produce a header differente in regular (non-customized) notifications, i.e. "text/plain".

File: test/functionalTest/cases/2893_case_insensitive_custom_notif_http_headers/case_insensitive_custom_notif_http_headers.test [hunk 11]
```diff
@@ -0,0 +1,153 @@
...
+      {
+        "id" : "E1"
+      }
+    ],
+    "condition": {
+      "attrs": []
+    }
+  },
+  "notification": {
+    "httpCustom": {
```
Comment (fgalan) [inline test/functionalTest/cases/2893_case_insensitive_custom_notif_http_headers/case_insensitive_custom_notif_http_headers.test]: Aligned with the comment at https://github.com/telefonicaid/fiware-orion/pull/3024/files?diff=unified#r146819562 about using plain text, you should add something like this:

```
"payload": "Attributes are: ${A1} - ${A2} - ${A3} - ${A4}
```

File: test/functionalTest/cases/2893_case_insensitive_custom_notif_http_headers/case_insensitive_custom_notif_http_headers.test (hunk 10 above)
Comment (fgalan) [reply test/functionalTest/cases/2893_case_insensitive_custom_notif_http_headers/case_insensitive_custom_notif_http_headers.test]: Actually, we could keep case_insensitive_custom_notif_http_headers.test as it is now and have the text plain version in a different file e.g. case_insensitive_custom_notif_http_headers_with_text_plain.test).

File: src/lib/rest/httpRequestSend.cpp [hunk 12]
```diff
@@ -406,45 +401,50 @@ int httpRequestSendWithCurl
     {
       // "Switching" protocol https -> http is needed in this case, as CB->Rush request will use HTTP
       protocol = "http://";
-      headerRushHttp = "X-relayer-protocol: https";
```
Comment (fgalan) [inline src/lib/rest/httpRequestSend.cpp]: This refactors part of the code related with "regular" headers. Have you tested a full regression with `make test` in oder to check that everything keeps ok?

File: src/lib/rest/httpRequestSend.cpp (hunk 3 above)
Comment (arigliano) [reply src/lib/rest/httpRequestSend.cpp]: Fixed in af759bc

File: src/lib/rest/httpRequestSend.cpp (hunk 2 above)
Comment (arigliano) [reply src/lib/rest/httpRequestSend.cpp]: Fixed in af759bc

File: src/lib/rest/httpRequestSend.cpp (hunk 4 above)
Comment (arigliano) [reply src/lib/rest/httpRequestSend.cpp]: Fixed in af759bc

File: src/lib/rest/httpRequestSend.cpp (hunk 5 above)
Comment (arigliano) [reply src/lib/rest/httpRequestSend.cpp]: Fixed in af759bc

File: src/lib/rest/httpRequestSend.cpp (hunk 8 above)
Comment (arigliano) [reply src/lib/rest/httpRequestSend.cpp]: Yes it is. Note old **ngis** vs fixed one **ngsi**

File: test/functionalTest/cases/2893_case_insensitive_custom_notif_http_headers/case_insensitive_custom_notif_http_headers.test (hunk 6 above)
Comment (arigliano) [reply test/functionalTest/cases/2893_case_insensitive_custom_notif_http_headers/case_insensitive_custom_notif_http_headers.test]: NTC

File: src/lib/rest/httpRequestSend.cpp (hunk 9 above)
Comment (arigliano) [reply src/lib/rest/httpRequestSend.cpp]: Yes it is. Note old ngis vs fixed one ngsi

File: src/lib/rest/httpRequestSend.cpp (hunk 7 above)
Comment (arigliano) [reply src/lib/rest/httpRequestSend.cpp]: Fixed in 59aea87

File: src/lib/rest/httpRequestSend.cpp (hunk 12 above)
Comment (arigliano) [reply src/lib/rest/httpRequestSend.cpp]: Yes, i did it. It seems to be fine.

File: test/functionalTest/cases/2893_case_insensitive_custom_notif_http_headers/case_insensitive_custom_notif_http_headers.test (hunk 10 above)
Comment (arigliano) [reply test/functionalTest/cases/2893_case_insensitive_custom_notif_http_headers/case_insensitive_custom_notif_http_headers.test]: Do you mean to create a new test with "A4": "text/plain" and then with an expected payload like the one you describe in the comment below?

Comment (fgalan) [reply test/functionalTest/cases/2893_case_insensitive_custom_notif_http_headers/case_insensitive_custom_notif_http_headers.test]: Right

File: src/lib/rest/httpRequestSend.cpp (hunk 12 above)
Comment (fgalan) [reply src/lib/rest/httpRequestSend.cpp]: NTC

File: src/lib/rest/httpRequestSend.cpp (hunk 8 above)
Comment (fgalan) [reply src/lib/rest/httpRequestSend.cpp]: Ah, ok, I didn't realized on the typo in the original code. Nice :)

NTC

File: src/lib/rest/httpRequestSend.cpp (hunk 9 above)
Comment (fgalan) [reply src/lib/rest/httpRequestSend.cpp]: Ah, ok, I didn't realized on the typo in the original code. Nice :)

NTC

File: test/functionalTest/cases/2893_case_insensitive_custom_notif_http_headers/case_insensitive_custom_notif_http_headers.test (hunk 10 above)
Comment (arigliano) [reply test/functionalTest/cases/2893_case_insensitive_custom_notif_http_headers/case_insensitive_custom_notif_http_headers.test]: Fixed in 5156484

File: test/functionalTest/cases/2893_case_insensitive_custom_notif_http_headers/case_insensitive_custom_notif_http_headers.test (hunk 11 above)
Comment (arigliano) [reply test/functionalTest/cases/2893_case_insensitive_custom_notif_http_headers/case_insensitive_custom_notif_http_headers.test]: Fixed in 5156484

**Comment by fgalan** [comment]
LGTM. Thank you for your contribution!

Passing the ball to @kzangeli for final LGTM

**Comment by kzangeli** [comment]
LGTM
