### PR TITLE
Bug #1289

### LINKED ISSUE #1289: [BUG] when is exceeded the index key limit in mongo
the index key limit in mongo is 1024, see issue https://github.com/telefonicaid/fiware-orion/issues/1283

if `type` or `id` exceed index key limit ,CB responds 201 and nothing is stored in mongo.

#### Request:
```
 POST http://qa-orion-fe-01:1026/v2/entities
  Content-Type: application/json
  Fiware-Service: test_entities_type
  Fiware-ServicePath: /test
  {"type": "TZQIpnz4YX7NgOo2DCSJ6llpviu6mG2Xc2H7MqPaJy9fGRtUcjg1UmguN39pwSKkFJpIJJ1n4RGwjJBkk5iGDl7OY1RW5dZRKQ6hKCSSufXZqm02ECdoqQWnjR6WZ5PGJMRpSmnrVbdZMKfXkJ04WiCUekxiLxgHM6ToydSt8XZ2yDdYcXpXBSVOx66bIi8CoImJAqLYc39apAF77hI1Y1RPksM1S8z9d5sVp0IxhnFN27Al72XXQDqwSTW7YUZyJJeXzM9OI4lQY0CnZLignlNqxiW8Hr4SfZrqWhailwIZ9Q6FyWfjhcSrWK2RF89kVkGIt9DuO7yaGQ5ONCessB2f8rab0CVvVC6WGafUtvDJs8raCQfEzMnLZ2PW6jDMFH1RXPAoxRN78Ho1QLgJB4YVqUWjgB4ZMQCWFQbaG0fSMAImLyzwqjSAoIbobooQzKjaL6aZzIYV1HlVsZSzrnlz68cHD62ZQxIjxsTjPjk2jlXAPCWi23KO4XOB3x9NrzYN2Eh0aN4VDCHfnFQWj4LkqoF2LbZLYonLLrty9yLRqUD1Sq4dpHO52HTWI6dh9LZI0oT4spnPHNmlnsifjatn3e6hmH6gFiXiyXKdndptaHUVaI8GwDr6zeQH0GYlfw4Ho46iaECauPbpgD9YONA0kAl8BFZpL83yz3pJyhRNK4vCWHS676PBEGr8GXBkwTScge5f2pACnvfNmHbrPtm1FHuZ6ZRH318hBt7p98XSF757lz3ML2ixoecLBORRTBgHto95feclNIyrbRgZ9LiOfQrifoagfhGh04eLN6dPCt3mXDmirYR6kU2xUGOmGug4QM1OKUyWUK8vPCqfG4iu4Klt9Pv2s1ttPHmloeEvZ580b7AODyxQqWhHbVJ0OmAJ02h14ONdkvGKDBBzcmh5cFiTDMZDRMFU88NnTQJkFoEBjtz6OYkRdR2U1ctpPXyYkFP0xednTNl6cC9oRz7vXiOXFDozYFPV3lZqeenIsPlQhFpqim11DxTdEbqM", "temperature": "34", "id": "room_1"}
```

#### Response
```
http code: 201
 content-length: 0
```

#### Log 
```
time=2015-09-25T08:56:09.696CEST | lvl=INFO | trans=1443164167-603-00000000003 | function=processContextElement | comp=Orion | msg=MongoCommonUpdate.cpp[2328]: Database Operation Successful ({ _id.id: "room_1", _id.type: "TZQIpnz4YX7NgOo2DCSJ6llpviu6mG2Xc2H7MqPaJy9fGRtUcjg1UmguN39pwSKkFJpIJJ1n4RGwjJBkk5iGDl7OY1RW5dZRKQ6hKCSSufXZqm02ECdoqQWnjR6WZ5PGJMRpSmnrVbdZMKfXkJ04Wi...", _id.servicePath: /^\/test$/ })
time=2015-09-25T08:56:09.696CEST | lvl=INFO | trans=1443164167-603-00000000003 | function=processContextElement | comp=Orion | msg=MongoCommonUpdate.cpp[2388]: Database Operation Successful ({ _id.id: "room_1", _id.type: "TZQIpnz4YX7NgOo2DCSJ6llpviu6mG2Xc2H7MqPaJy9fGRtUcjg1UmguN39pwSKkFJpIJJ1n4RGwjJBkk5iGDl7OY1RW5dZRKQ6hKCSSufXZqm02ECdoqQWnjR6WZ5PGJMRpSmnrVbdZMKfXkJ04Wi...", _id.servicePath: /^\/test$/ })
time=2015-09-25T08:56:09.698CEST | lvl=ERROR | trans=1443164167-603-00000000003 | function=createEntity | comp=Orion | msg=MongoCommonUpdate.cpp[1993]: Database Error (Database Error: collection: orion.entities - insert(): { _id: { id: "room_1", type: "TZQIpnz4YX7NgOo2DCSJ6llpviu6mG2Xc2H7MqPaJy9fGRtUcjg1UmguN39pwSKkFJpIJJ1n4RGwjJBkk5iGDl7OY1RW5dZRKQ6hKCSSufXZqm02ECdoqQWnjR6WZ5PGJMRpSmnrVbdZMKfXkJ04Wi...", servicePath: "/test" }, attrNames: [ "temperature" ], attrs: { temperature: { type: "", creDate: 1443164169, modDate: 1443164169, value: "34" } }, creDate: 1443164169, modDate: 1443164169 } - exception: OperationException: { index: 0, code: 17280, errmsg: "insertDocument :: caused by :: 17280 Btree::insert: key too large to index, failing orion.entities.$_id_ 1086 { : { id: "room_1", type: "TZQIpnz4YX7Ng...", op: { _id: { id: "room_1", type: "TZQIpnz4YX7NgOo2DCSJ6llpviu6mG2Xc2H7MqPaJy9fGRtUcjg1UmguN39pwSKkFJpIJJ1n4RGwjJBkk5iGDl7OY1RW5dZRKQ6hKCSSufXZqm02ECdoqQWnjR6WZ5PGJMRpSmnrVbdZMKfXkJ04Wi...", servicePath: "/test" }, attrNames: [ "temperature" ], attrs: { temperature: { type: "", creDate: 1443164169, modDate: 1443164169, value: "34" } }, creDate: 1443164169, modDate: 1443164169 } })

```

### PR DESCRIPTION
**Pull request by fortizc**
Fixes #1289

### CODE REVIEW

File: src/lib/serviceRoutinesV2/postEntities.cpp [hunk 1]
```diff
@@ -34,6 +34,12 @@
 #include "serviceRoutines/postUpdateContext.h"
 
 
+static bool legalEntityLength(Entity* eP, const std::string &servicePath)
+{
+  const int constant = 10;
```
Comment (fgalan) [inline src/lib/serviceRoutinesV2/postEntities.cpp]: I'd suggest to use a #define in the file preamble (i.e. just after the #include lines):

```
#define STRUCTURAL_OVERHEAD_BSON_ID 10
```

(The name is to align with the terms used by MongoDB documentation... "contant" is too broad)

File: src/lib/serviceRoutinesV2/postEntities.cpp [hunk 2]
```diff
@@ -34,6 +34,12 @@
 #include "serviceRoutines/postUpdateContext.h"
```
Comment (fgalan) [inline src/lib/serviceRoutinesV2/postEntities.cpp]: A line in CHANGE_NEXT_RELEASE about the issue fix should be added (have a look to the current CHANGES_NEXT_RELEASE file, it is plenty of examples :)

File: test/functionalTest/cases/1289_exceed_mongo_key_limit/exceed_mongo_key_limit.test [hunk 3]
```diff
@@ -0,0 +1,86 @@
...
+{
+    "description": "The requested entity has not been found. Check type and id",
+    "error": "NotFound"
+}
+
+
+--TEARDOWN--
+brokerStop CB
+dbDrop CB
+
```
Comment (fgalan) [inline test/functionalTest/cases/1289_exceed_mongo_key_limit/exceed_mongo_key_limit.test]: Please add the following to manuals/user/known_limitations.md (at the end) of the file to document this new limitation:

```
## Entity fields length limitation

Due to limitations at MongoDB layer, the lenght of entity ID, type and servicePath has to follow the following rule.

length(id) + length(type) + length(servicePath) + 10 < 1024

Otherwise, we will get and error at entity creation time.
```

File: test/functionalTest/cases/1289_exceed_mongo_key_limit/exceed_mongo_key_limit.test [hunk 4]
```diff
@@ -0,0 +1,86 @@
...
+--SHELL-INIT--
+dbInit CB
+brokerStart CB 0
+
+--SHELL--
+
+#
+# 01. POST /v2/entities (Room1-Room)
+# 02. POST /v2/entities (Room1-Room)
```
Comment (fgalan) [inline test/functionalTest/cases/1289_exceed_mongo_key_limit/exceed_mongo_key_limit.test]: Typo: this should be "02. GET /v2/entities/Room1"

File: test/functionalTest/cases/1289_exceed_mongo_key_limit/exceed_mongo_key_limit.test [hunk 5]
```diff
@@ -0,0 +1,86 @@
+# Copyright 2015 Telefonica Investigacion y Desarrollo, S.A.U
```
Comment (fgalan) [inline test/functionalTest/cases/1289_exceed_mongo_key_limit/exceed_mongo_key_limit.test]: I'd suggest to create a "parallel" .test (e.g. exceed_mongo_key_limit.test
) to cover this funcionality also in /v1. For example:

01. POST /v1/updateContext (using in the payload an entity id/type violating the constraint), you have examples of how to do updateContext in existing .test
02. GET /v1/contextEntities/Room1

File: src/lib/serviceRoutinesV2/postEntities.cpp (hunk 1 above)
Comment (fortizc) [inline src/lib/serviceRoutinesV2/postEntities.cpp]: But for modern C and C++ the recommendation is use constants instead of #define maybe create a global file scoped constant? something like:
statict const int STRUCTURAL_OVERHEAD_BSON_ID = 10;

File: test/functionalTest/cases/1289_exceed_mongo_key_limit/exceed_mongo_key_limit.test (hunk 4 above)
Comment (fortizc) [inline test/functionalTest/cases/1289_exceed_mongo_key_limit/exceed_mongo_key_limit.test]: Fix in 03dddc660c42fa0029ddda13be1fe11624d58a19

File: test/functionalTest/cases/1289_exceed_mongo_key_limit/exceed_mongo_key_limit.test (hunk 3 above)
Comment (fortizc) [inline test/functionalTest/cases/1289_exceed_mongo_key_limit/exceed_mongo_key_limit.test]: Fixed in 42f63eaf46d51b86d203e9caef42501ef4bf39ec

Comment (fgalan) [inline test/functionalTest/cases/1289_exceed_mongo_key_limit/exceed_mongo_key_limit.test]: The render is a bit weird (everything in the same line):

2015-10-28 21_12_43-add new know limitation see issue 1289 telefonicaid_fiware-orion 42f63ea

Probably you need to add some empty lines.

File: src/lib/serviceRoutinesV2/postEntities.cpp (hunk 2 above)
Comment (fortizc) [inline src/lib/serviceRoutinesV2/postEntities.cpp]: Fixed in 1a4a968d7077c3943a23a396f8c7bbb654dce8fc

File: src/lib/serviceRoutinesV2/postEntities.cpp (hunk 1 above)
Comment (fgalan) [inline src/lib/serviceRoutinesV2/postEntities.cpp]: #define (the one that we typically use in CB) has the advantage of pre-processor text replacement (i.e. faster code... although maybe marginally faster) while static const has the advantage of allowing semantics in the constant (so it is treated as `int` in every place were it is used). 

Both are ok, not an important issue at this point (use the one you prefer).

Comment (fortizc) [inline src/lib/serviceRoutinesV2/postEntities.cpp]: Fixed in 618422ee731b3896bd061782e740afb6dbb76de3

File: test/functionalTest/cases/1289_exceed_mongo_key_limit/exceed_mongo_key_limit.test (hunk 3 above)
Comment (fortizc) [inline test/functionalTest/cases/1289_exceed_mongo_key_limit/exceed_mongo_key_limit.test]: Fixed in 606c4123b41fd71fb7c473ad8cd2b182ee38bc0f

File: CHANGES_NEXT_RELEASE [hunk 6]
```diff
@@ -32,3 +32,4 @@ Fix:  Improve error description in NGSIv2 PUT entity, when entity is not found
 Add:  Hardening: mongoBackend checking for field existence and proper type to avoid broker crashes due to DB corruption (Issue #136)
 Add:  githash in --version (Issue #1363)
 Add:  Added CLI argument for notification mode. Default mode is 'transient' (previous version used 'permanent' implicitly) (Issue #1370)
+Fix:  [BUG] when is exceeded the index key limit in mongo (Issue #1289)
```
Comment (kzangeli) [inline CHANGES_NEXT_RELEASE]: wording: Return error response when the (mongo) index key limit is exceeded

File: doc/manuals/user/known_limitations.md [hunk 7]
```diff
@@ -49,3 +49,11 @@ Required" response. This is due to the way the underlying HTTP library
 (microhttpd) works, see details in [this email thread in the microhttpd
 mailing
 list](http://lists.gnu.org/archive/html/libmicrohttpd/2014-01/msg00063.html).
+
+## Entity fields length limitation
+
+Due to limitations at MongoDB layer, the lenght of entity ID, type and servicePath has to follow the following rule.
```
Comment (kzangeli) [inline doc/manuals/user/known_limitations.md]: typo: lenght => length

File: doc/manuals/user/known_limitations.md [hunk 8]
```diff
@@ -49,3 +49,11 @@ Required" response. This is due to the way the underlying HTTP library
...
+
+    length(id) + length(type) + length(servicePath) + 10 < 1024
+
+Otherwise, we will get and error at entity creation time.
```
Comment (kzangeli) [inline doc/manuals/user/known_limitations.md]: type: and => an

File: src/lib/serviceRoutinesV2/postEntities.cpp [hunk 9]
```diff
@@ -33,6 +33,12 @@
 #include "serviceRoutinesV2/postEntities.h"
 #include "serviceRoutines/postUpdateContext.h"
 
+static const int STRUCTURAL_OVERHEAD_BSON_ID = 10;
+
+static bool legalEntityLength(Entity* eP, const std::string &servicePath)
```
Comment (kzangeli) [inline src/lib/serviceRoutinesV2/postEntities.cpp]: style guide: three empty lines and a function header for each function

File: test/functionalTest/cases/1289_exceed_mongo_key_limit/exceed_mongo_key_limit.test [hunk 10]
```diff
@@ -0,0 +1,86 @@
...
+--SHELL-INIT--
+dbInit CB
+brokerStart CB 0
+
+--SHELL--
+
+#
+# 01. POST /v2/entities (Room1)
+# 02. POST /v2/entities (Room1)
+#
```
Comment (kzangeli) [inline test/functionalTest/cases/1289_exceed_mongo_key_limit/exceed_mongo_key_limit.test]: Try to explain what is tested, E.g.:

    # 01. Trying to create an entity with TOO LONG entityId
    # 02. Making sure no entity was created in part 01

File: CHANGES_NEXT_RELEASE (hunk 6 above)
Comment (fortizc) [inline CHANGES_NEXT_RELEASE]: Fixed ef5279a202107dd86bd176247e1cecbf294ab710

File: doc/manuals/user/known_limitations.md (hunk 7 above)
Comment (fortizc) [inline doc/manuals/user/known_limitations.md]: Fixed d2b8fd8b04343df74f63fa9404eeeb62acfac909

File: doc/manuals/user/known_limitations.md (hunk 8 above)
Comment (fortizc) [inline doc/manuals/user/known_limitations.md]: Fixed in 8484dfb5e323a8782243eef1465c0fbb96ba87ef

File: test/functionalTest/cases/1289_exceed_mongo_key_limit/exceed_mongo_key_limit.test (hunk 10 above)
Comment (fortizc) [inline test/functionalTest/cases/1289_exceed_mongo_key_limit/exceed_mongo_key_limit.test]: Fix in c7cb6d6bb16187935b3e8cb24c7dbf4a3e9e1f2a

File: test/functionalTest/cases/1289_exceed_mongo_key_limit/exceed_mongo_key_limit.test (hunk 5 above)
Comment (fortizc) [inline test/functionalTest/cases/1289_exceed_mongo_key_limit/exceed_mongo_key_limit.test]: what if I create a folder named  1289_exceed_mongo_key_limit_v2 for this test and use the current folder for the V1 test

File: src/lib/serviceRoutinesV2/postEntities.cpp (hunk 9 above)
Comment (fortizc) [inline src/lib/serviceRoutinesV2/postEntities.cpp]: Fixed in 66d94b1a8b34ed5d11e1194e103ca1e8b51c8e1a

File: test/functionalTest/cases/1289_exceed_mongo_key_limit/exceed_mongo_key_limit.test (hunk 5 above)
Comment (fgalan) [inline test/functionalTest/cases/1289_exceed_mongo_key_limit/exceed_mongo_key_limit.test]: I think is better to use the existing folder (1289_exceed_mongo_key_limit/) and create a new .test file inside it (exceed_mongo_key_limit_v1.test) as it is part of the same topic/issue and using two folders will lead to an excesive "fragmentation".

Comment (fgalan) [inline test/functionalTest/cases/1289_exceed_mongo_key_limit/exceed_mongo_key_limit.test]: Test deferred to a next PR. NTC.

**Comment by fgalan** [comment]
LGTM

File: test/functionalTest/cases/1289_exceed_mongo_key_limit/exceed_mongo_key_limit.test (hunk 10 above)
Comment (kzangeli) [inline test/functionalTest/cases/1289_exceed_mongo_key_limit/exceed_mongo_key_limit.test]: As a general rule, try to use the **exact same** text in all three places in the test (header, shell, regexpect).
This test is very short, so no probs.

NTC

**Comment by kzangeli** [comment]
LGTM, but must be merged with develop before we can merge
