### PR TITLE
FIX metadata filter crashes and compound filtering bug

### LINKED ISSUE #2496: CB crashes if a subscriptions use "mq" condition with a metadata unknown
CB crashes if a subscription uses "mq" condition field with a metadata unknown.

#### CB config:
```
contextBroker -fg -dbhost <mongo_host> -db orion -multiservice -t 0-255 -logLevel DEBUG -noCache
```

#### subscription request
```
http://localhost:1026/v2/subscriptions
Fiware-Service: test_happy_path
Fiware-ServicePath: /test
Content-Type: application/json
 {"notification": {"http": {"url": "http://localhost:1045/notify"}}, "subject": {"entities": [{"idPattern": ".*"}], "condition": {"expression": {"mq": "temperature.sdfdfs==56"}}}}
```

#### entity request
```
http://localhost:1026/v2/entities
Fiware-Service: test_happy_path
Fiware-ServicePath: /test
Content-Type: application/json
{"type": "house", "id": "room15",  "temperature":{"type": "celsius", "metadata": {"meta_temperature": {"value": 34, "type": "alarm"}}, "value": 34}}
```

#### log messages:
```
DEBUG@14:03:08  MongoCommonUpdate.cpp[1524]: adding subscription: '{ _id: ObjectId('57cd7b093756ace7b45dc126'), expiration: 9000000000000000000, reference: "http://10.95.233.86:1045/notify", custom: false, throttling: 0, servicePath: "/test", status: "active", entities: [ { id: ".*", isPattern: "true" } ], attrs: [], blacklist: false, conditions: [], expression: { q: "", mq: "temperature.sdfdfs==56", geometry: "", coords: "", georel: "" }, format: "normalized" }'
DEBUG@14:03:08  ContextAttribute.cpp[208]: Creating a ContextAttribute: compoundValueP at (nil) for attribute 'temperature' at 0x7fb768002bc0
DEBUG@14:03:08  ContextAttribute.cpp[213]: Copying metadata 0
DEBUG@14:03:08  Metadata.cpp[84]: 'cloning' a Metadata
```

If we remove the subscription or the metadata in `mq` does exist, the entity is create correctly and CB does not crash:
```
DEBUG@14:06:52  ContextAttribute.cpp[213]: Copying metadata 0
DEBUG@14:06:52  Metadata.cpp[84]: 'cloning' a Metadata
DEBUG@14:06:52  sem.cpp[353]: mongoUpdateContext gives the 'req' semaphore for 'ngsi10 update request'
DEBUG@14:06:52  restReply.cpp[68]: Response 1: responding with 0 bytes, Status Code 201
DEBUG@14:06:52  restReply.cpp[69]: Response payload: ''
DEBUG@14:06:52  UpdateContextResponse.cpp[76]: destroyed
DEBUG@14:06:52  RegisterContextResponse.cpp[55]: destroyed
INFO@14:06:52  logMsg.h[1892]: Transaction ended
```

### PR DESCRIPTION
**Pull request by fgalan**
Fixes #2496 and additional (not reported yet) bug.

### CODE REVIEW

File: src/lib/rest/StringFilter.cpp [hunk 1]
```diff
@@ -1922,12 +1922,38 @@ bool StringFilter::mqMatch(ContextElementResponse* cerP)
     ContextAttribute*  caP   = cerP->contextElement.getAttribute(itemP->attributeName);
     Metadata*          mdP   = (caP == NULL)? NULL : caP->metadataVector.lookupByName(itemP->metadataName);
 
-    if ((itemP->op == SfopExists) && (mdP == NULL))
+    if ((itemP->op == SfopExists) || (itemP->op == SfopNotExists))
```
Comment (fgalan) [inline src/lib/rest/StringFilter.cpp]: Now, the logic is the same as the one usef for qMatch()

NTC (just informative)

File: test/functionalTest/cases/1156_mqfilters_and_compounds/mqfilters_and_compounds_existence_subs.test [hunk 2]
```diff
@@ -25,7 +25,6 @@ String filters for compound values of attributes: existence in subscriptions
 
 --SHELL-INIT--
 dbInit CB
-#brokerStart CB 0 IPv4 -noCache
```
Comment (fgalan) [inline test/functionalTest/cases/1156_mqfilters_and_compounds/mqfilters_and_compounds_existence_subs.test]: An old leftover... in theory no longer needed as the jenkins test harness pass now run twice (for no-cache an cache cases).

NTC (just informative).

File: test/functionalTest/cases/1156_mqfilters_and_compounds/mqfilters_and_compounds_existence_subs.test [hunk 3]
```diff
@@ -46,7 +45,8 @@ accumulatorStart --pretty-print
 # 12. Create subscription 6 for mq=!A1.M2.i - notification
 # 13. Dump and reset accumulator, see one notification
 # 14. Update E1, to provoke another 3 notifications
-# 15. Dump and reset accumulator, see three notifications
+# 15. Dump and reset accumulator, see three notifications (sub1, sub4 and sub6)
```
Comment (fgalan) [inline test/functionalTest/cases/1156_mqfilters_and_compounds/mqfilters_and_compounds_existence_subs.test]: The modifications in this .test are related with "Fix: wrong matching in metadata existence and not existence filters with compounds" fix.

It could seem that the .test has not been actually notified. However, up to know it was wrong: notifications in step 15 were for sub1 (ok), sub2 (wrong) and sub6 (ok). Now the outcome is corret and step 16 has been added to ensure that.

NTC (just informative)

**Comment by iariasleon** [comment]
LGTM
