### PR TITLE
FIX lost sp in update context subscription

### LINKED ISSUE #1693: Subscription service path is lost at update subscription time
Initial state: subscripion S1 at SP /ss1, then updating S1 with SP /ss1 will make SP desapears (check at DB).

At least, it happens in NGSIv1 operations.

### PR DESCRIPTION
**Pull request by fgalan**
Fixes #1693

### CODE REVIEW

File: src/lib/mongoBackend/MongoGlobal.cpp [hunk 1]
```diff
@@ -2386,7 +2385,6 @@ bool processOnChangeConditionForSubscription
       ContextElementResponseVector  allCerV;
       AttributeList                 emptyList;
 
-      // FIXME P10: we are using a dummy scope for the moment, until subscription scopes get implemented
```
Comment (fgalan) [inline src/lib/mongoBackend/MongoGlobal.cpp]: I forgot to remove these couple of FIXME P10 in a previous PR, sorry...

NTC

**Comment by kzangeli** [comment]
LGTM
