### PR TITLE
fix Issue3468

### LINKED ISSUE #3468: POST /v2/registrations allows forbidden attribute names in NGSIv2
(This comes from https://github.com/telefonicaid/fiware-orion/issues/3068#issuecomment-481668521)

According to that report, CB is allowing a POST /v2/registration with attribute `luminescence att` and it must not, given the whitespace is forbidden in attribute names in NGSIv2 according the spec.

Probably it is a matter of adjusting the parsing logic to be more strict. Let's have a look to the parsing for create entity logic, where I think these cheking are already in place and working.

CC: @dcalvoalonso

### PR DESCRIPTION
**Pull request by rajeswar-NEC**
fixed #3468

### CODE REVIEW

**Comment by rajeswar-NEC** [comment]
Hi @fgalan 

I've fixed the issue #3468. Please check it and if it is ok then please merge the PR in master branch.

File: src/lib/jsonParseV2/parseStringVector.cpp [hunk 1]
```diff
@@ -68,6 +69,12 @@ bool parseStringVector
 
     std::string value = iter->GetString();
 
+    if (forbiddenIdCharsV2(value.c_str()))
+    {
+      *errorStringP = "forbidden characters in attribute name";
```
Comment (fgalan) [inline src/lib/jsonParseV2/parseStringVector.cpp:74]: PR should include a .test covering the case. I mean, a .test with just one step, sending a registration with forbbiden char in attribute name and checking that the corresponding 400 Bad Request is responsed.

**Comment by rajeswar-NEC** [comment]
Hi @fgalan

I've added a new test case for forbidden characters in attribute name
and it is executing successfully.

**Comment by Chandradeep-NEC** [comment]
@fgalan 
As this PR has been reviewed by you. Request you to merge the PR in master if your comments are incorporated.

File: test/functionalTest/cases/3468_v2_registrations_attribute_name_with_forbidden_character/attribute_name_with_forbidden_character.test [hunk 2]
```diff
@@ -0,0 +1,81 @@
...
+
+
+--SHELL-INIT--
+dbInit CB
+brokerStart CB 0
+
+--SHELL--
+
+#
+# 01. POST /v2/registrations Forbidden character in attribute name
```
Comment (fgalan) [inline test/functionalTest/cases/3468_v2_registrations_attribute_name_with_forbidden_character/attribute_name_with_forbidden_character.test:34]: To make the test even better :) I'd suggest to add some more cases:

```
 # 02. POST /v2/registrations Forbidden character in attribute type
 # 03. POST /v2/registrations Forbidden character in entity id
 # 04. POST /v2/registrations Forbidden character in entity type
```

Comment (rajeswar-NEC) [reply test/functionalTest/cases/3468_v2_registrations_attribute_name_with_forbidden_character/attribute_name_with_forbidden_character.test:34]: Hi @fgalan 
> To make the test even better :) I'd suggest to add some more cases:
# 02. POST /v2/registrations Forbidden character in attribute type
# 03. POST /v2/registrations Forbidden character in entity id
# 04. POST /v2/registrations Forbidden character in entity type

As per “POST /v2/registrations” API payload mentioned in API walkthrough, I’m able to create test cases for forbidden  character in “entity id” and “entity type”.
But in case of  forbidden character in “attribute type” I’m unable to create it because “attribute type” is not present in “POST /v2/registrations” API  payload.

   "attrs": [
      "temperature",
      "pressure"
    ]

Even I’ve tried with adding “attribute type” in payload but unable to create it.
I’ve checked “POST /v1/registry” API payload, in this payload “attribute type” is present.
Please confirm my understanding.

         "attributes": [
                {
                    "name": "temperature",
                    "type": "float",
                    "isDomain": "false"
                },
                {
                    "name": "pressure",
                    "type": "integer",
                    "isDomain": "false"
                }
            ],

Comment (fgalan) [reply test/functionalTest/cases/3468_v2_registrations_attribute_name_with_forbidden_character/attribute_name_with_forbidden_character.test:34]: Yes, you are right. Please ignore the attributes type case in my original suggestion.

Comment (rajeswar-NEC) [reply test/functionalTest/cases/3468_v2_registrations_attribute_name_with_forbidden_character/attribute_name_with_forbidden_character.test:34]: Hi @fgalan 
I've added new test case for entity type and entity id

**Review by fgalan — APPROVED** [review]
LGTM. Thanks!
