### PR TITLE
Bug/issue 1026

### LINKED ISSUE #1016: "longjmp causes uninitialized stack frame" crash
Detected in Orion 0.22.0.

Orion crashes with the following trace:

```
*** longjmp causes uninitialized stack frame ***: contextBroker terminated
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(__fortify_fail+0x37)[0x7f9be328efe7]
/lib/x86_64-linux-gnu/libc.so.6(+0xf0f79)[0x7f9be328ef79]
/lib/x86_64-linux-gnu/libc.so.6(__longjmp_chk+0x33)[0x7f9be328eee3]
/usr/lib/x86_64-linux-gnu/libcurl.so.4(+0xd385)[0x7f9be475d385]
/lib/x86_64-linux-gnu/libpthread.so.0(+0xf0a0)[0x7f9be43300a0]
/lib/x86_64-linux-gnu/libc.so.6(nanosleep+0x2d)[0x7f9be324a2bd]
/lib/x86_64-linux-gnu/libc.so.6(sleep+0xe0)[0x7f9be324a130]
contextBroker(main+0x90a)[0x4c20fa]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xfd)[0x7f9be31bcead]
contextBroker[0x4d4d99]
======= Memory map: ========
00400000-0076a000 r-xp 00000000 08:01 523319                             /home/fermin/bin/contextBroker
0096a000-00975000 rw-p 0036a000 08:01 523319                             /home/fermin/bin/contextBroker
00975000-009bd000 rw-p 00000000 00:00 0 
02104000-02a9a000 rw-p 00000000 00:00 0                                  [heap]
7f9bd46d4000-7f9bd46d6000 r-xp 00000000 08:01 663926                     /lib/libnss_mdns4.so.2
7f9bd46d6000-7f9bd48d6000 ---p 00002000 08:01 663926                     /lib/libnss_mdns4.so.2
7f9bd48d6000-7f9bd48d7000 rw-p 00002000 08:01 663926                     /lib/libnss_mdns4.so.2
7f9bd48d7000-7f9bd48dc000 r-xp 00000000 08:01 662367                     /lib/x86_64-linux-gnu/libnss_dns-2.13.so
7f9bd48dc000-7f9bd4adb000 ---p 00005000 08:01 662367                     /lib/x86_64-linux-gnu/libnss_dns-2.13.so
7f9bd4adb000-7f9bd4adc000 r--p 00004000 08:01 662367                     /lib/x86_64-linux-gnu/libnss_dns-2.13.so
7f9bd4adc000-7f9bd4add000 rw-p 00005000 08:01 662367                     /lib/x86_64-linux-gnu/libnss_dns-2.13.so
7f9bd4add000-7f9bd4adf000 r-xp 00000000 08:01 663928                     /lib/libnss_mdns4_minimal.so.2
7f9bd4adf000-7f9bd4cde000 ---p 00002000 08:01 663928                     /lib/libnss_mdns4_minimal.so.2
7f9bd4cde000-7f9bd4cdf000 rw-p 00001000 08:01 663928                     /lib/libnss_mdns4_minimal.so.2
7f9bd4cdf000-7f9bd4cea000 r-xp 00000000 08:01 662369                     /lib/x86_64-linux-gnu/libnss_files-2.13.so
7f9bd4cea000-7f9bd4ee9000 ---p 0000b000 08:01 662369                     /lib/x86_64-linux-gnu/libnss_files-2.13.so
7f9bd4ee9000-7f9bd4eea000 r--p 0000a000 08:01 662369                     /lib/x86_64-linux-gnu/libnss_files-2.13.so
7f9bd4eea000-7f9bd4eeb000 rw-p 0000b000 08:01 662369                     /lib/x86_64-linux-gnu/libnss_files-2.13.so
7f9bd4f00000-7f9bdcf00000 rw-p 00000000 00:00 0 
7f9bdcf00000-7f9bdcf01000 ---p 00000000 00:00 0 
7f9bdcf01000-7f9bdd701000 rw-p 00000000 00:00 0 
7f9bdd701000-7f9bdd702000 ---p 00000000 00:00 0 
7f9bdd702000-7f9bddf02000 rw-p 00000000 00:00 0 
7f9bddf02000-7f9bddf03000 ---p 00000000 00:00 0 
7f9bddf03000-7f9bde703000 rw-p 00000000 00:00 0 
7f9bde703000-7f9bde715000 r-xp 00000000 08:01 415698                     /usr/lib/x86_64-linux-gnu/pkcs11/gnome-keyring-pkcs11.so
7f9bde715000-7f9bde915000 ---p 00012000 08:01 415698                     /usr/lib/x86_64-linux-gnu/pkcs11/gnome-keyring-pkcs11.so
7f9bde915000-7f9bde917000 rw-p 00012000 08:01 415698                     /usr/lib/x86_64-linux-gnu/pkcs11/gnome-keyring-pkcs11.so
7f9bde917000-7f9bde91a000 r-xp 00000000 08:01 654237                     /lib/x86_64-linux-gnu/libgpg-error.so.0.8.0
7f9bde91a000-7f9bdeb19000 ---p 00003000 08:01 654237                     /lib/x86_64-linux-gnu/libgpg-error.so.0.8.0
7f9bdeb19000-7f9bdeb1a000 rw-p 00002000 08:01 654237                     /lib/x86_64-linux-gnu/libgpg-error.so.0.8.0
7f9bdeb1a000-7f9bdeb2b000 r-xp 00000000 08:01 397001                     /usr/lib/x86_64-linux-gnu/libp11-kit.so.0.0.0
7f9bdeb2b000-7f9bded2a000 ---p 00011000 08:01 397001                     /usr/lib/x86_64-linux-gnu/libp11-kit.so.0.0.0
7f9bded2a000-7f9bded2b000 r--p 00010000 08:01 397001                     /usr/lib/x86_64-linux-gnu/libp11-kit.so.0.0.0
7f9bded2b000-7f9bded2c000 rw-p 00011000 08:01 397001                     /usr/lib/x86_64-linux-gnu/libp11-kit.so.0.0.0
7f9bded2c000-7f9bded3c000 r-xp 00000000 08:01 408525                     /usr/lib/x86_64-linux-gnu/libtasn1.so.3.1.16
7f9bded3c000-7f9bdef3b000 ---p 00010000 08:01 408525                     /usr/lib/x86_64-linux-gnu/libtasn1.so.3.1.16
7f9bdef3b000-7f9bdef3c000 r--p 0000f000 08:01 408525                     /usr/lib/x86_64-linux-gnu/libtasn1.so.3.1.16
7f9bdef3c000-7f9bdef3d000 rw-p 00010000 08:01 408525                     /usr/lib/x86_64-linux-gnu/libtasn1.so.3.1.16
7f9bdef3d000-7f9bdef40000 r-xp 00000000 08:01 662390                     /lib/x86_64-linux-gnu/libkeyutils.so.1.4
7f9bdef40000-7f9bdf13f000 ---p 00003000 08:01 662390                     /lib/x86_64-linux-gnu/libkeyutils.so.1.4
7f9bdf13f000-7f9bdf140000 r--p 00002000 08:01 662390                     /lib/x86_64-linux-gnu/libkeyutils.so.1.4
7f9bdf140000-7f9bdf141000 rw-p 00003000 08:01 662390                     /lib/x86_64-linux-gnu/libkeyutils.so.1.4
7f9bdf141000-7f9bdf149000 r-xp 00000000 08:01 400361                     /usr/lib/x86_64-linux-gnu/libkrb5support.so.0.1
7f9bdf149000-7f9bdf348000 ---p 00008000 08:01 400361                     /usr/lib/x86_64-linux-gnu/libkrb5support.so.0.1
7f9bdf348000-7f9bdf349000 r--p 00007000 08:01 400361                     /usr/lib/x86_64-linux-gnu/libkrb5support.so.0.1
7f9bdf349000-7f9bdf34a000 rw-p 00008000 08:01 400361                     /usr/lib/x86_64-linux-gnu/libkrb5support.so.0.1
7f9bdf34a000-7f9bdf34d000 r-xp 00000000 08:01 654161                     /lib/x86_64-linux-gnu/libcom_err.so.2.1
7f9bdf34d000-7f9bdf54c000 ---p 00003000 08:01 654161                     /lib/x86_64-linux-gnu/libcom_err.so.2.1
7f9bdf54c000-7f9bdf54d000 r--p 00002000 08:01 654161                     /lib/x86_64-linux-gnu/libcom_err.so.2.1
7f9bdf54d000-7f9bdf54e000 rw-p 00003000 08:01 654161                     /lib/x86_64-linux-gnu/libcom_err.so.2.1
7f9bdf54e000-7f9bdf574000 r-xp 00000000 08:01 425457                     /usr/lib/x86_64-linux-gnu/libk5crypto.so.3.1
7f9bdf574000-7f9bdf774000 ---p 00026000 08:01 425457                     /usr/lib/x86_64-linux-gnu/libk5crypto.so.3.1
7f9bdf774000-7f9bdf775000 r--p 00026000 08:01 425457                     /usr/lib/x86_64-linux-gnu/libk5crypto.so.3.1
7f9bdf775000-7f9bdf776000 rw-p 00027000 08:01 425457                     /usr/lib/x86_64-linux-gnu/libk5crypto.so.3.1
7f9bdf776000-7f9bdf777000 rw-p 00000000 00:00 0 
7f9bdf777000-7f9bdf840000 r-xp 00000000 08:01 425467                     /usr/lib/x86_64-linux-gnu/libkrb5.so.3.3
7f9bdf840000-7f9bdfa3f000 ---p 000c9000 08:01 425467                     /usr/lib/x86_64-linux-gnu/libkrb5.so.3.3Abortado
```

This bug has been detected associated to the CPrs forwarding functionalities, in scenarios were a given query/update could be forwarded to ~1,000 CPrs (e.g. a queryContext in id=".*", isPattern="true", type="" match all the registrations and the Orion instance in FIWARE Lab have around ~1000 activer registrations).

This seems to be a known problem in libcurl (see http://stackoverflow.com/questions/9191668/error-longjmp-causes-uninitialized-stack-frame). In that post, it is sayd that libcurl 7.32 solves the problem, but the version in CentOS 6.x (our reference OS) is 7.19. Thus, the best option seems to be set the CURLOPT_NOSINGAL option (http://curl.haxx.se/libcurl/c/CURLOPT_NOSIGNAL.html).

In addition, it would be useful to implement some kind of "forwarding cap" to avoid a absurdly large number of forwards, e.g. it doesn't make sense to do 1,000 sequential forwards to CPr resolve a query (specially if they are done in a sequential way). In typical uses case, as much as 5-10 forwards seem to be a number large enougth. This could be implemented with a CLI parameter, e.g. `-cprForwardLimit`.

### PR DESCRIPTION
**Pull request by crbrox**
Fixes #1016 

@fgalan

### CODE REVIEW

File: CHANGES_NEXT_RELEASE [hunk 1]
```diff
@@ -5,4 +5,5 @@ Add: New operation "GET /v2" (Issue #956)
 Fix: ONCHANGE subscription sends notification when value under condition it is not updated with updateContext-APPEND in some cases (Issue #943)
 Add: Reuse curl context for outgoing notifications, so now connections are persistent if the HTTP server doesn't close them
 Fix: remove unconditional tracing on xmlTreat()/jsonTreat() which was impacting on performance (specially in high-load scenarios)
+Fix: issue 1016, use NOSIGNAL in libcurl plus command line argument to limit forwarded requests
```
Comment (fgalan) [inline CHANGES_NEXT_RELEASE]: I would suggest to split into two lines in the following way:

```
Fix: use NOSIGNAL as libcurl option to avoid crashes in that library. (Issue #1016)
Add: CLI paramter -cprForwardLimit to cap the number of forwarding request for a single client request. (Issue #1016).

File: src/lib/rest/httpRequestSend.cpp [hunk 2]
```diff
@@ -395,6 +395,9 @@ std::string httpRequestSend
   curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, &writeMemoryCallback); // Send data here
   curl_easy_setopt(curl, CURLOPT_WRITEDATA, (void*) httpResponse); // Custom data for response handling
 
+  // To solve issue 1016
```
Comment (fgalan) [inline src/lib/rest/httpRequestSend.cpp]: I would susggest to replace this comment for some more informative, like this:

"There is a known problem in libcurl (see http://stackoverflow.com/questions/9191668/error-longjmp-causes-uninitialized-stack-frame) which is solved using CURLOPT_NOSIGNAL. If we update some day from libcurl 7.19 (the one that comes with CentOS 6.x) to a newer version (there are some reports about the bug is no longer in libcurl 7.32), using CURLOPT_NOSIGNAL could be not necessary and this be removed). See issue #1016 for more details"

File: CHANGES_NEXT_RELEASE (hunk 1 above)
Comment (crbrox) [inline CHANGES_NEXT_RELEASE]: Fixed 7fd91ad6645cb9

File: src/lib/rest/httpRequestSend.cpp (hunk 2 above)
Comment (crbrox) [inline src/lib/rest/httpRequestSend.cpp]: Fixed 0361d9058cbb87c6e36fe0aa889502524437253f

**Comment by crbrox** [comment]
LGTM

**Comment by fgalan** [comment]
LGTM
