### PR TITLE
FIX over-logging of Runtime Error traces not representing actual error

### LINKED ISSUE #2597: Avoid over-logging Runtime Error not actually being errors
Currently there is a lot of Runtime Errors that are not actullay so, due the way safeMongo.cpp funtions are used.

### PR DESCRIPTION
**Pull request by fgalan**
Fixes #2597 for the master branch

### CODE REVIEW

File: src/lib/mongoBackend/safeMongo.cpp [hunk 1]
```diff
@@ -290,16 +290,17 @@ void setStringVector
...
-  // Detect error
-  if (!b.hasField(field))
-  {
-    LM_E(("Runtime Error (object field '%s' is missing in BSONObj <%s> from caller %s:%d)", field.c_str(), b.toString().c_str(), caller.c_str(), line));
-  }
-  else
-  {
-    LM_E(("Runtime Error (field '%s' was supposed to be an array but type=%d in BSONObj <%s> from caller %s:%d)",
-          field.c_str(), b.getField(field).type(), b.toString().c_str(), caller.c_str(), line));
+  else {
```
Comment (fgalan) [inline src/lib/mongoBackend/safeMongo.cpp]: I think this is the casue of the errors recently reported by @iariasleon and @jmcanterafonseca

Comment (kzangeli) [inline src/lib/mongoBackend/safeMongo.cpp]: Aha, I see you have put the error inside an 'else' that didn't exist before. That explains the strange behaviour ...

**Comment by kzangeli** [comment]
LGTM
